name: Workflow Demo

on: [push]

env:
  WORKFLOW: "Variable at the workflow level"

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt
        

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download text file
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: ./artifacts
    - name: Display content of the text file
      run: cat ./artifacts/hello.txt
    
  job:
    runs-on: ubuntu-latest
    env:
      JOB: "Variable at the job level"

    steps:
    - name: step level
      env: 
        STEP: "This variable is at the step level"
      run: echo ${STEP}

    - name: job level
      run: echo ${JOB}
    - name: workflow-var
      run: echo ${WORKFLOW}

    - name: vars
      run: echo ${{ vars.VAR }}

    - name: secrets
      run:  echo ${{ secrets.SECRET }}